name: user_repository
description: "Dart package wich manage the user"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  firebase_auth: ^4.19.2
  cloud_firestore: ^4.17.1
  firebase_storage: ^11.7.4
  firebase_core: ^2.30.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true